query getPlayers($partyId: String!, $userId: Int) {
    user(where: { id: $userId }) {
        id
        postedCount
        solvedCount
    }
    party(where: { id: $partyId }) {
        id
        users(orderBy: { score: desc }) {
            id
            username
            score
        }
    }
}
