query GetRengas($partyId: String!, $first: Int!, $skip: Int!) {
    rengas(
        where: { partyId: { equals: $partyId } }
        orderBy: { createdAt: desc }
        first: $first
        skip: $skip
    ) {
        id
        emojis
        author {
            id
            username
        }
        createdAt
        deletedAt
        status {
            isResolved
            isMine
        }
    }
}
