query GetRengas(
    $partyId: String!
    $first: Int!
    $skip: Int!
    $orderBy: QueryRengasOrderByInput!
) {
    rengas(
        where: { partyId: { equals: $partyId } }
        orderBy: $orderBy
        first: $first
        skip: $skip
    ) {
        id
        emojis
        author {
            id
            username
        }
        createdAt
        deletedAt
        status {
            isResolved
            isMine
        }
    }
}
