query GetPlaylistRengas($playlistId: String!) {
    playlistRengas(where: { playlistId: { equals: $playlistId } }) {
        id
        emojis
    }
}

mutation TryPlaylistRenga($rengaId: Int!, $movieId: Int!) {
    tryPlaylistRenga(rengaId: $rengaId, movieDBId: $movieId)
}
