query GetPlaylistRengas($playlistId: String!) {
    playlistRengas(where: { playlistId: { equals: $playlistId } }) {
        id
        emojis
        title
    }
}

mutation TryPlaylistRenga($rengaId: Int!, $movieId: Int!) {
    tryPlaylistRenga(rengaId: $rengaId, movieDBId: $movieId)
}

mutation CreatePlaylist(
    $playlistId: String!
    $rengas: [PlaylistRengaCreateWithoutPlaylistInput!]
) {
    createOnePlaylist(data: { id: $playlistId, rengas: { create: $rengas } }) {
        id
        rengas {
            id
            emojis
            title
        }
    }
}
